module: SKTiled
module_version: 1.12
author: Michael Fessenden
author_url: https://github.com/mfessenden
github_url: https://github.com/mfessenden/SKTiled
github_file_prefix: https://github.com/mfessenden/SKTiled/tree/1.12    # url of source file links on server
root_url: https://mfessenden.github.io/SKTiled                         # absolute url of file location on server
clean: true
skip_undocumented: true
output: docs/jazzy_output
readme: docs/Start.md
docset_icon: images/icon-16x16.png
min_acl: public
skip_undocumented: true
hide_documentation_coverage: true

exclude:
  - "**/*-ObjC.swift"
  - "Sources/SKTiled+Extensions.swift"

copyright: '© 2016 [Michael Fessenden](https://github.com/mfessenden) under [open source license](https://github.com/mfessenden/SKTiled/tree/master/LICENSE).'
swift_version: 3.1

theme: apple

documentation:
  - docs/Tutorial/Coordinates.md
  - docs/Tutorial/Debugging.md
#  - docs/Tutorial/Extending.md
#  - docs/Tutorial/GameplayKit.md
  - docs/Tutorial/Getting Started.md
  - docs/Tutorial/Layers.md
  - docs/Tutorial/Objects.md
  - docs/Tutorial/Properties.md
  - docs/Tutorial/Scenes.md
  - docs/Tutorial/Tiles.md
  - docs/Tutorial/Troubleshooting.md

abstract: docs/Sections/*.md

custom_categories:
  - name: Tutorial    # references the section page
    children:
      - Getting Started
      - Scenes
      - Layers
      - Tiles
      - Coordinates
      - Objects
      - Properties
#      - GameplayKit
#      - Extending
      - Debugging
      - Troubleshooting

  - name: Protocols
    children:
    - SKTiledObject
    - SKTilemapDelegate
    - SKTiledSceneDelegate

  - name: Class Reference  # references the section page
    children:
    - SKTilemap
    - SKTilemapParser
    - SKTileset
    - SKTilesetData
    - TiledLayerObject
    - SKTileLayer
    - SKObjectGroup
    - SKImageLayer
    - SKGroupLayer
    - SKTile
    - SKTileObject
    - SKTiledScene
    - SKTiledSceneCamera

  - name: Other
    children:
    - TilemapOrientation
    - SKObjectType
    - TileOffset
    - CollisionType
    - PhysicsShape
    - SKTiledLayerType
